name: Publish NuGet Package

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    environment: Package Creation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Ensure packages directory exists
      run: New-Item -ItemType Directory -Force -Path ./nupkgs

    - name: Restore dependencies
      run: dotnet restore ./LogViewer/LogViewer.csproj
      env:
        nuget-api-key: ${{ secrets.GH_PKG_TOKEN }}

    - name: Build the project
      run: dotnet build ./LogViewer/LogViewer.csproj --configuration Release

    - name: Test
      run: dotnet test ./LogViewer.Tests/LogViewer.Tests.csproj --configuration Release

    - name: Build and pack
      run: dotnet pack ./LogViewer/LogViewer.csproj --configuration Release --output ./nupkgs

    - name: List nupkgs contents
      run: Get-ChildItem ./nupkgs

    - name: Publish to GitHub Packages
      run: |
        Get-ChildItem ./nupkgs -Include *.nupkg,*.snupkg -Recurse | ForEach-Object {
          Write-Host "Publishing $($_.Name)"
          dotnet nuget push $_.FullName --source "github" --api-key $env:NUGET_TOKEN --skip-duplicate
        }
      env:
        NUGET_TOKEN: ${{ secrets.GH_PKG_TOKEN }}
