name: Publish NuGet Package

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    environment: Package Creation

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
      
    - name: List working directory
      run: pwd
    
    - name: Ensure packages directory exists
      run: mkdir -p ./nupkgs
    
    - name: Restore dependencies
      run: dotnet restore ./LogViewer/LogViewer.csproj
      env:
        nuget-api-key: ${{ secrets.GH_PKG_TOKEN }}

    - name: Build the project
      run: dotnet build ./LogViewer/LogViewer.csproj --configuration Release

    - name: Test
      run: dotnet test ./LogViewer.Tests/LogViewer.Tests.csproj --configuration Release

    - name: Build and pack
      run: dotnet pack ./LogViewer/LogViewer.csproj --configuration Release --output ./nupkgs

    - name: List nupkgs contents
      run: dir ./nupkgs/*.nupkg

    - name: List working directory
      run: pwd

    - name: Publish to GitHub Packages
      run: |
        for file in ./nupkgs/**.nupkg ./nupkgs/**.snupkg; do
          echo "Publishing $file"
          dotnet nuget push "$file" --source "github" --api-key ${{ secrets.GH_PKG_TOKEN }}
        done
      shell: bash
      env:
        nuget-api-key: ${{ secrets.GH_PKG_TOKEN }}